[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on   = "T"
run  = "close"
desc = "Close current tab"

[[mgr.prepend_keymap]]
on   = "n"
run  = "create"
desc = "Create new file/folder"
